### ISSUE TITLE
README.md shows incorrect netty and netty-tcnative dependencies

### ISSUE THREAD

**Issue by lagrangian-mech** [relayrides/pushy#532]
The README.md file still mentions netty 4.1.14 and netty-tcnative 2.0.5.Final.

But the 0.11.3 release description says there's been an upgrade to the latest netty and the actual issue and commit that changes the dependencies to 4.1.14 and 2.0.6.Final respectively show up as completed in the 0.11.3 milestone.

**Comment by jchambers** [comment]
Thanks. Fixed in 109439f.

Did I mention yet that it's a bad idea to do a release while on cold meds? ;)

**Comment by lagrangian-mech** [comment]
I just realized I wasn't clear enough/thorough enough.  The problem isn't just the README.md file, but the fact that the version of the README.md that displays on the home page is wrong. You did fix the README.md file in that commit, but the home page is still showing the wrong thing.

Right now if you go to https://github.com/relayrides/pushy the home page text (incorrectly!) says that the current release is 0.11.1 and that the dependencies are netty 4.1.14.Final and netty-tcnative 2.0.5.Final.
